// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// quad-build.cpp
integers quad_index_cpp(integers nx, integers ny, logicals ydown);
extern "C" SEXP _textures_quad_index_cpp(SEXP nx, SEXP ny, SEXP ydown) {
  BEGIN_CPP11
    return cpp11::as_sexp(quad_index_cpp(cpp11::as_cpp<cpp11::decay_t<integers>>(nx), cpp11::as_cpp<cpp11::decay_t<integers>>(ny), cpp11::as_cpp<cpp11::decay_t<logicals>>(ydown)));
  END_CPP11
}
// quad-build.cpp
doubles quad_vertex_cpp(integers nx, integers ny, logicals ydown, logicals zh);
extern "C" SEXP _textures_quad_vertex_cpp(SEXP nx, SEXP ny, SEXP ydown, SEXP zh) {
  BEGIN_CPP11
    return cpp11::as_sexp(quad_vertex_cpp(cpp11::as_cpp<cpp11::decay_t<integers>>(nx), cpp11::as_cpp<cpp11::decay_t<integers>>(ny), cpp11::as_cpp<cpp11::decay_t<logicals>>(ydown), cpp11::as_cpp<cpp11::decay_t<logicals>>(zh)));
  END_CPP11
}
// quad-build.cpp
writable::doubles_matrix<> quad_vertex_matrix_cpp(integers nx, integers ny, logicals ydown, logicals zh);
extern "C" SEXP _textures_quad_vertex_matrix_cpp(SEXP nx, SEXP ny, SEXP ydown, SEXP zh) {
  BEGIN_CPP11
    return cpp11::as_sexp(quad_vertex_matrix_cpp(cpp11::as_cpp<cpp11::decay_t<integers>>(nx), cpp11::as_cpp<cpp11::decay_t<integers>>(ny), cpp11::as_cpp<cpp11::decay_t<logicals>>(ydown), cpp11::as_cpp<cpp11::decay_t<logicals>>(zh)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_textures_quad_index_cpp",         (DL_FUNC) &_textures_quad_index_cpp,         3},
    {"_textures_quad_vertex_cpp",        (DL_FUNC) &_textures_quad_vertex_cpp,        4},
    {"_textures_quad_vertex_matrix_cpp", (DL_FUNC) &_textures_quad_vertex_matrix_cpp, 4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_textures(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
