// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// quad_index_cpp
IntegerVector quad_index_cpp(IntegerVector nx, IntegerVector ny);
RcppExport SEXP _textures_quad_index_cpp(SEXP nxSEXP, SEXP nySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ny(nySEXP);
    rcpp_result_gen = Rcpp::wrap(quad_index_cpp(nx, ny));
    return rcpp_result_gen;
END_RCPP
}
// quad_vertex_cpp
NumericVector quad_vertex_cpp(IntegerVector nx, IntegerVector ny);
RcppExport SEXP _textures_quad_vertex_cpp(SEXP nxSEXP, SEXP nySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ny(nySEXP);
    rcpp_result_gen = Rcpp::wrap(quad_vertex_cpp(nx, ny));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_textures_quad_index_cpp", (DL_FUNC) &_textures_quad_index_cpp, 2},
    {"_textures_quad_vertex_cpp", (DL_FUNC) &_textures_quad_vertex_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_textures(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
