# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quad_index_cpp <- function(nx, ny) {
    .Call(`_textures_quad_index_cpp`, nx, ny)
}

quad_vertex_cpp <- function(nx, ny) {
    .Call(`_textures_quad_vertex_cpp`, nx, ny)
}

