# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quad_index <- function(nx, ny) {
    .Call(`_textures_quad_index`, nx, ny)
}

quad_vertex <- function(nx, ny) {
    .Call(`_textures_quad_vertex`, nx, ny)
}

